version: '3.7'
services:
  wordpress:
    image: wordpress
    container_name: wp-wordpress
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    volumes:
      - /efs/website:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_CONFIG: wp_
